/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface BatchTransferContractInterface extends utils.Interface {
  functions: {
    "batchTransfer(address[],uint256[])": FunctionFragment;
    "batchTransferCombinedMultiTokens(address[],address[],uint256[],address[],uint256[])": FunctionFragment;
    "batchTransferMultiTokens(address[],address[],uint256[])": FunctionFragment;
    "batchTransferToken(address,address[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchTransfer"
      | "batchTransferCombinedMultiTokens"
      | "batchTransferMultiTokens"
      | "batchTransferToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchTransfer",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferCombinedMultiTokens",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferMultiTokens",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferCombinedMultiTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferMultiTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferToken",
    data: BytesLike
  ): Result;

  events: {
    "BatchTransfer(address,address[],uint256[])": EventFragment;
    "BatchTransferCombinedMultiTokens(address,address[],address[],uint256[],address[],uint256[])": EventFragment;
    "BatchTransferMultiToken(address,address[],address[],uint256[])": EventFragment;
    "BatchTransferToken(address,address,address[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchTransfer"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BatchTransferCombinedMultiTokens"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BatchTransferMultiToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BatchTransferToken"): EventFragment;
}

export interface BatchTransferEventObject {
  fromAddress: string;
  toAddress: string[];
  recipientAmount: BigNumber[];
}
export type BatchTransferEvent = TypedEvent<
  [string, string[], BigNumber[]],
  BatchTransferEventObject
>;

export type BatchTransferEventFilter = TypedEventFilter<BatchTransferEvent>;

export interface BatchTransferCombinedMultiTokensEventObject {
  fromAddress: string;
  tokenAddress: string[];
  tokenRecipientAddress: string[];
  tokenAmount: BigNumber[];
  recipients: string[];
  amount: BigNumber[];
}
export type BatchTransferCombinedMultiTokensEvent = TypedEvent<
  [string, string[], string[], BigNumber[], string[], BigNumber[]],
  BatchTransferCombinedMultiTokensEventObject
>;

export type BatchTransferCombinedMultiTokensEventFilter =
  TypedEventFilter<BatchTransferCombinedMultiTokensEvent>;

export interface BatchTransferMultiTokenEventObject {
  fromAddress: string;
  tokenAddress: string[];
  toAddress: string[];
  recipientAmount: BigNumber[];
}
export type BatchTransferMultiTokenEvent = TypedEvent<
  [string, string[], string[], BigNumber[]],
  BatchTransferMultiTokenEventObject
>;

export type BatchTransferMultiTokenEventFilter =
  TypedEventFilter<BatchTransferMultiTokenEvent>;

export interface BatchTransferTokenEventObject {
  fromAddress: string;
  tokenAddress: string;
  toAddress: string[];
  recipientAmount: BigNumber[];
}
export type BatchTransferTokenEvent = TypedEvent<
  [string, string, string[], BigNumber[]],
  BatchTransferTokenEventObject
>;

export type BatchTransferTokenEventFilter =
  TypedEventFilter<BatchTransferTokenEvent>;

export interface BatchTransferContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BatchTransferContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTransferCombinedMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      tokenRecipients: PromiseOrValue<string>[],
      tokenAmounts: PromiseOrValue<BigNumberish>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTransferMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  batchTransfer(
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTransferCombinedMultiTokens(
    tokenAddress: PromiseOrValue<string>[],
    tokenRecipients: PromiseOrValue<string>[],
    tokenAmounts: PromiseOrValue<BigNumberish>[],
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTransferMultiTokens(
    tokenAddress: PromiseOrValue<string>[],
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTransferToken(
    tokenAddress: PromiseOrValue<string>,
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchTransferCombinedMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      tokenRecipients: PromiseOrValue<string>[],
      tokenAmounts: PromiseOrValue<BigNumberish>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchTransferMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BatchTransfer(address,address[],uint256[])"(
      fromAddress?: null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferEventFilter;
    BatchTransfer(
      fromAddress?: null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferEventFilter;

    "BatchTransferCombinedMultiTokens(address,address[],address[],uint256[],address[],uint256[])"(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string>[] | null,
      tokenRecipientAddress?: null,
      tokenAmount?: null,
      recipients?: PromiseOrValue<string>[] | null,
      amount?: null
    ): BatchTransferCombinedMultiTokensEventFilter;
    BatchTransferCombinedMultiTokens(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string>[] | null,
      tokenRecipientAddress?: null,
      tokenAmount?: null,
      recipients?: PromiseOrValue<string>[] | null,
      amount?: null
    ): BatchTransferCombinedMultiTokensEventFilter;

    "BatchTransferMultiToken(address,address[],address[],uint256[])"(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string>[] | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferMultiTokenEventFilter;
    BatchTransferMultiToken(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string>[] | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferMultiTokenEventFilter;

    "BatchTransferToken(address,address,address[],uint256[])"(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferTokenEventFilter;
    BatchTransferToken(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferTokenEventFilter;
  };

  estimateGas: {
    batchTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTransferCombinedMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      tokenRecipients: PromiseOrValue<string>[],
      tokenAmounts: PromiseOrValue<BigNumberish>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTransferMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTransferCombinedMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      tokenRecipients: PromiseOrValue<string>[],
      tokenAmounts: PromiseOrValue<BigNumberish>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTransferMultiTokens(
      tokenAddress: PromiseOrValue<string>[],
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
