/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface BatchTokenContractInterface extends utils.Interface {
  functions: {
    "batchTransferToken(address,address[],uint256[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "batchTransferToken"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchTransferToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchTransferToken",
    data: BytesLike
  ): Result;

  events: {
    "BatchTransfer(address,address,address[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchTransfer"): EventFragment;
}

export interface BatchTransferEventObject {
  fromAddress: string;
  tokenAddress: string;
  toAddress: string[];
  recipientAmount: BigNumber[];
}
export type BatchTransferEvent = TypedEvent<
  [string, string, string[], BigNumber[]],
  BatchTransferEventObject
>;

export type BatchTransferEventFilter = TypedEventFilter<BatchTransferEvent>;

export interface BatchTokenContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BatchTokenContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  batchTransferToken(
    tokenAddress: PromiseOrValue<string>,
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BatchTransfer(address,address,address[],uint256[])"(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferEventFilter;
    BatchTransfer(
      fromAddress?: PromiseOrValue<string> | null,
      tokenAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<string>[] | null,
      recipientAmount?: null
    ): BatchTransferEventFilter;
  };

  estimateGas: {
    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchTransferToken(
      tokenAddress: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
